### ISSUE TITLE
Add Projects

### ISSUE THREAD

**Issue by mubaris** [opencode18/opencode18.github.io#45]
[OpenCode'18 Mentors (Responses) - Form Responses 1.pdf](https://github.com/opencode18/opencode18.github.io/files/1623629/OpenCode.18.Mentors.Responses.-.Form.Responses.1.pdf)

Add all the projects which are not available on the website. Check the file uploaded

**Comment by Re42** [comment]
I'd like to work on this

**Comment by mubaris** [comment]
@Re42 You're assigned

CC: @gauthamzz @Anupam-dagar @aswanthkoleri @aswinzz

**Comment by Anupam-dagar** [comment]
@Re42 please don't add goal coach

**Comment by Re42** [comment]
@Anupam-dagar my pr was merged, should I make a new one?

**Comment by Anupam-dagar** [comment]
@Re42 make a new PR removing goal coach
